### ISSUE TITLE
deployed chart for tftpd ... how to validate it can be used?

### ISSUE THREAD

**Issue by strus38** [pojntfx/charts#1]
hi
Looking at using your chart tftpd to help pxe booting some servers.
I have deployed it:
` 
kubectl get pods -n coredns

NAME                            READY   STATUS    RESTARTS   AGE

lab-coredns-67c469fbd7-55j8v    1/1     Running   0          21h

lab-coredns-67c469fbd7-gzcfx    1/1     Running   1          21h

tftpdd-tftpd-5b9d99fb96-78drp   1/1     Running   0          3m31s
`

`
kubectl get svc -n coredns

NAME           TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                       AGE

kube-dns-tcp   LoadBalancer   10.105.179.161   192.168.1.180   53:30797/TCP,9153:31083/TCP   21h

kube-dns-udp   LoadBalancer   10.100.224.215   192.168.1.180   53:30798/UDP                  21h

tftpdd-tftpd   ClusterIP      10.98.224.134    <none>          1040/TCP                      3m49s
`

Now, how can I check it is running and how can I test a pxe boot scenorio? (my first PXE attempt, so a newbie question).
Thanks!

**Comment by pojntfx** [comment]
Hey! The best place to start using `tftpdd` (I'm still working on a centralized place for docs) are the two following repos:

- https://github.com/pojntfx/virtual-datacenter: This is a basic "step-by-step" tutorial for working with the system
- https://pojntfx.github.io/tftpdd/: There are some docs in the GitHub repo as well.

In case you need any help, feel free to ask - I'm still new to documentation and having public projects that people actually use ;)

**Comment by pojntfx** [comment]
Closing due to timeout
